### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by ghost** [unitcurrency/unitcurrency#3]
The COPYING file has been omitted, this is a copyright violation.

**Comment by koko2530** [comment]
Hi, 
What is file ?
How to get right?
Thanks

**Comment by ghost** [comment]
https://github.com/bitcoin/bitcoin/blob/0.8/COPYING
Just copy it back into the top-level folder.

**Comment by unitcurrency** [comment]
success,
https://github.com/unitcurrency/unitcurrency/blob/master/LICENSE

**Comment by ghost** [comment]
Good job.
